#!/usr/bin/env python3
"""
IoT Device Simulator — Zerobus gRPC SDK
=========================================
Reads config from config.json (generated by setup_local.py).
Asks for SP credentials on first run.

Usage:
    pip install databricks-zerobus-ingest-sdk
    python iot_device_simulator.py
"""

import os
import sys
import time
import json
import random
import signal
import logging
import getpass
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("iot-sim-grpc")

running = True
def stop(s, f):
    global running
    log.info("Stopping...")
    running = False
signal.signal(signal.SIGINT, stop)
signal.signal(signal.SIGTERM, stop)


def load_config():
    """Load config from config.json and prompt for missing values."""
    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")

    if os.path.exists(config_path):
        with open(config_path) as f:
            config = json.load(f)
    else:
        print("config.json not found. Run setup_local.py first, or enter values manually:\n")
        config = {}

    def get(key, label, default="", secret=False):
        val = os.environ.get(key) or default
        if not val:
            if secret:
                val = getpass.getpass(f"  {label}: ")
            else:
                val = input(f"  {label} [{default}]: ") or default
        return val

    workspace_url = get("DATABRICKS_WORKSPACE_URL", "Workspace URL", config.get("workspace_url", ""))
    catalog = get("DATABRICKS_CATALOG", "Catalog", config.get("catalog", ""))
    schema = get("DATABRICKS_SCHEMA", "Schema", config.get("schema", ""))
    zerobus = get("ZEROBUS_SERVER_ENDPOINT", "Zerobus endpoint", config.get("zerobus_endpoint", ""))
    table = config.get("table", "") or f"{catalog}.{schema}.iot_events_raw"
    client_id = get("DATABRICKS_CLIENT_ID", "SP Client ID", config.get("client_id", ""))
    client_secret = get("DATABRICKS_CLIENT_SECRET", "SP Client Secret", config.get("client_secret", ""), secret=True)

    if not all([workspace_url, catalog, schema, zerobus, client_id, client_secret]):
        log.error("Missing required configuration.")
        sys.exit(1)

    return {
        "workspace_url": workspace_url,
        "catalog": catalog,
        "schema": schema,
        "zerobus_endpoint": zerobus,
        "table": table,
        "client_id": client_id,
        "client_secret": client_secret,
    }


def create_stream(endpoint, workspace_url, client_id, client_secret, table):
    from zerobus.sdk.sync import ZerobusSdk
    from zerobus.sdk.shared import RecordType, StreamConfigurationOptions, TableProperties
    log.info(f"Connecting: {endpoint} -> {table}")
    sdk = ZerobusSdk(endpoint, workspace_url)
    stream = sdk.create_stream(client_id, client_secret, TableProperties(table),
        StreamConfigurationOptions(record_type=RecordType.JSON))
    log.info("Connected!")
    return sdk, stream


def generate_event(device_id, anomaly_rate):
    is_anomaly = random.random() < anomaly_rate
    if is_anomaly:
        temp = round(random.uniform(42.0, 58.0), 2)
        hum = round(random.choice([random.uniform(3.0, 12.0), random.uniform(93.0, 99.5)]), 2)
    else:
        temp = round(random.uniform(18.0, 35.0), 2)
        hum = round(random.uniform(35.0, 75.0), 2)
    return {
        "device_id": device_id,
        "temperature": temp,
        "humidity": hum,
        "pressure": round(random.uniform(995.0, 1025.0), 2),
        "event_time": int(datetime.now(timezone.utc).timestamp() * 1_000_000),
        "source": "zerobus",
    }


def main():
    cfg = load_config()
    table = cfg["table"]
    # Validate: must be exactly catalog.schema.table (3 parts)
    parts = table.split(".")
    if len(parts) != 3:
        log.error(f"Invalid table name '{table}' — must be catalog.schema.table (3 parts, got {len(parts)})")
        log.error(f"Fix 'table' in config.json")
        sys.exit(1)
    num_devices = int(os.environ.get("NUM_DEVICES", "5"))
    eps = float(os.environ.get("EVENTS_PER_SECOND", "2"))
    anomaly_rate = float(os.environ.get("ANOMALY_RATE", "0.1"))
    devices = [f"sensor-{i:03d}" for i in range(1, num_devices + 1)]

    log.info("=" * 60)
    log.info("IoT Simulator — Zerobus gRPC SDK")
    log.info(f"  Endpoint: {cfg['zerobus_endpoint']}")
    log.info(f"  Table:    {table}")
    log.info(f"  Devices:  {num_devices} | Rate: {eps}/sec | Anomaly: {anomaly_rate*100:.0f}%")
    log.info("=" * 60)

    try:
        _, stream = create_stream(
            cfg["zerobus_endpoint"], cfg["workspace_url"],
            cfg["client_id"], cfg["client_secret"], table)
    except Exception as e:
        log.error(f"Connection failed: {e}")
        log.error("Install: pip install databricks-zerobus-ingest-sdk")
        sys.exit(1)

    interval = 1.0 / eps
    total = 0

    log.info("Press Ctrl+C to stop.\n")

    try:
        while running:
            event = generate_event(random.choice(devices), anomaly_rate)
            is_anomaly = event["temperature"] > 40 or event["humidity"] > 90 or event["humidity"] < 20
            log.info(f"[{event['device_id']}] temp={event['temperature']}C hum={event['humidity']}%{'  *** ANOMALY ***' if is_anomaly else ''}")

            try:
                stream.ingest_record_nowait(event)
                total += 1
            except Exception as e:
                log.error(f"Send error: {e}")
                try:
                    stream.close()
                    _, stream = create_stream(
                        cfg["zerobus_endpoint"], cfg["workspace_url"],
                        cfg["client_id"], cfg["client_secret"], table)
                except Exception:
                    pass

            if total % 10 == 0:
                try:
                    stream.flush()
                except Exception:
                    pass

            time.sleep(interval + random.uniform(-0.1, 0.1))
    finally:
        try:
            stream.flush()
            stream.close()
        except Exception:
            pass

    log.info(f"Done: {total} events.")


if __name__ == "__main__":
    main()
