#!/usr/bin/env python3
"""
IoT Device Simulator — SQL REST API
====================================
Reads config from config.json (generated by setup_local.py).
Asks for SP credentials on first run.

Usage:
    pip install requests
    python iot_simulator_rest.py
"""

import os
import sys
import time
import json
import random
import signal
import logging
import getpass
import requests
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("iot-sim")

running = True
def stop(s, f):
    global running
    log.info("Stopping...")
    running = False
signal.signal(signal.SIGINT, stop)
signal.signal(signal.SIGTERM, stop)


def load_config():
    """Load config from config.json and prompt for missing values."""
    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")

    if os.path.exists(config_path):
        with open(config_path) as f:
            config = json.load(f)
    else:
        print("config.json not found. Run setup_local.py first, or enter values manually:\n")
        config = {}

    def get(key, label, default="", secret=False):
        val = os.environ.get(key) or config.get(key.lower().replace("databricks_", "").replace("sql_", ""), "") or default
        if not val:
            if secret:
                val = getpass.getpass(f"  {label}: ")
            else:
                val = input(f"  {label} [{default}]: ") or default
        return val

    workspace_url = get("DATABRICKS_WORKSPACE_URL", "Workspace URL", config.get("workspace_url", ""))
    catalog = get("DATABRICKS_CATALOG", "Catalog", config.get("catalog", ""))
    schema = get("DATABRICKS_SCHEMA", "Schema", config.get("schema", ""))
    warehouse_id = get("DATABRICKS_SQL_WAREHOUSE_ID", "Warehouse ID", config.get("warehouse_id", ""))
    table = config.get("table", "") or f"{catalog}.{schema}.iot_events_raw"
    client_id = get("DATABRICKS_CLIENT_ID", "SP Client ID", config.get("client_id", ""))
    client_secret = get("DATABRICKS_CLIENT_SECRET", "SP Client Secret", config.get("client_secret", ""), secret=True)

    if not all([workspace_url, catalog, schema, warehouse_id, client_id, client_secret]):
        log.error("Missing required configuration.")
        sys.exit(1)

    return {
        "workspace_url": workspace_url,
        "catalog": catalog,
        "schema": schema,
        "warehouse_id": warehouse_id,
        "table": table,
        "client_id": client_id,
        "client_secret": client_secret,
    }


def get_token(workspace_url, client_id, client_secret):
    resp = requests.post(f"{workspace_url}/oidc/v1/token", data={
        "grant_type": "client_credentials", "client_id": client_id,
        "client_secret": client_secret, "scope": "all-apis"})
    if resp.status_code != 200:
        log.error(f"Auth failed: {resp.status_code} - {resp.text}")
        sys.exit(1)
    return resp.json()["access_token"]


def generate_event(device_id, anomaly_rate):
    is_anomaly = random.random() < anomaly_rate
    if is_anomaly:
        temp = round(random.uniform(42.0, 58.0), 2)
        hum = round(random.choice([random.uniform(3.0, 12.0), random.uniform(93.0, 99.5)]), 2)
    else:
        temp = round(random.uniform(18.0, 35.0), 2)
        hum = round(random.uniform(35.0, 75.0), 2)
    return {
        "device_id": device_id,
        "temperature": temp,
        "humidity": hum,
        "pressure": round(random.uniform(995.0, 1025.0), 2),
        "event_time": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z",
        "source": "zerobus",
    }


def send_batch(workspace_url, token, warehouse_id, table, events):
    values = ", ".join(
        f"('{e['device_id']}', {e['temperature']}, {e['humidity']}, "
        f"{e['pressure']}, '{e['source']}', '{e['event_time']}')"
        for e in events
    )
    resp = requests.post(f"{workspace_url}/api/2.0/sql/statements",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={"warehouse_id": warehouse_id,
              "statement": f"INSERT INTO {table} (device_id, temperature, humidity, pressure, source, event_time) VALUES {values}",
              "wait_timeout": "20s"})
    return resp.json().get("status", {}).get("state", "UNKNOWN")


def main():
    cfg = load_config()
    table = cfg["table"]
    parts = table.split(".")
    if len(parts) != 3:
        log.error(f"Invalid table name '{table}' — must be catalog.schema.table (3 parts, got {len(parts)})")
        log.error(f"Fix 'table' in config.json")
        sys.exit(1)
    num_devices = int(os.environ.get("NUM_DEVICES", "5"))
    eps = float(os.environ.get("EVENTS_PER_SECOND", "2"))
    anomaly_rate = float(os.environ.get("ANOMALY_RATE", "0.1"))
    devices = [f"sensor-{i:03d}" for i in range(1, num_devices + 1)]

    log.info("=" * 60)
    log.info("IoT Simulator — SQL REST API")
    log.info(f"  Workspace: {cfg['workspace_url']}")
    log.info(f"  Table:     {table}")
    log.info(f"  Devices:   {num_devices} | Rate: {eps}/sec | Anomaly: {anomaly_rate*100:.0f}%")
    log.info("=" * 60)

    log.info("Authenticating...")
    token = get_token(cfg["workspace_url"], cfg["client_id"], cfg["client_secret"])
    log.info("OK! Press Ctrl+C to stop.\n")

    interval = 1.0 / eps
    total = 0
    batch = []

    while running:
        event = generate_event(random.choice(devices), anomaly_rate)
        is_anomaly = event["temperature"] > 40 or event["humidity"] > 90 or event["humidity"] < 20
        log.info(f"[{event['device_id']}] temp={event['temperature']}C hum={event['humidity']}%{'  *** ANOMALY ***' if is_anomaly else ''}")

        batch.append(event)
        total += 1

        if len(batch) >= 5:
            state = send_batch(cfg["workspace_url"], token, cfg["warehouse_id"], table, batch)
            if state != "SUCCEEDED":
                log.warning(f"State: {state}")
            batch = []

        if total % 100 == 0:
            try:
                token = get_token(cfg["workspace_url"], cfg["client_id"], cfg["client_secret"])
            except Exception:
                pass

        time.sleep(interval + random.uniform(-0.1, 0.1))

    if batch:
        send_batch(cfg["workspace_url"], token, cfg["warehouse_id"], table, batch)

    log.info(f"Done: {total} events.")


if __name__ == "__main__":
    main()
